
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const EMPLOYEE_LIST = "EMPLOYEE_LIST"
export const EMPLOYEE_LOADED ="EMPLOYEE_LOADED"
export const GET_EMPLOYEE_LIST_FAIL = "GET_EMPLOYEE_LIST_FAIL"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const DELETED_EMPLOYEE = "DELETED_EMPLOYEE"
export const DELETE_FAIL = "DELETE_FAIL"
export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const ADDED_EMPLOYEE = "ADDED_EMPLOYEE"
export const ADD_EMPLOYEE_FAIL = "ADD_EMPLOYEE_FAIL"
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID"
export const GET_EMPLOYEE_BY_ID_OK = "GET_EMPLOYEE_BY_ID_OK"
export const GET_EMPLOYEE_BY_ID_ERR = "GET_EMPLOYEE_BY_ID_ERR"
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL"
export const UPDATED_EMPLOYEE = "UPDATED_EMPLOYEE"
export const EMPLOYEE_UPDATING = "EMPLOYEE_UPDATING"
